name: opticell
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.8.0
  shared_preferences: ^2.3.0
  flutter_local_notifications: ^17.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.2
  share_plus: ^10.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/splash_logo.png
    - assets/app_icon.jpeg