// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlqW5-yq8cZDcDUK-W_dKiTByXSskW9gY',
    appId: '1:902742693556:web:40018b6f4555709e23e9e1',
    messagingSenderId: '902742693556',
    projectId: 'opticellfinal',
    authDomain: 'opticellfinal.firebaseapp.com',
    storageBucket: 'opticellfinal.firebasestorage.app',
    measurementId: 'G-ZFWVZTCP4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkckNZgw6VZBhOGJhwa5x3YYDjAd0uoT4',
    appId: '1:902742693556:android:5a6add35ad250a9623e9e1',
    messagingSenderId: '902742693556',
    projectId: 'opticellfinal',
    storageBucket: 'opticellfinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnBcq0UznnDBenUK4RqZRzeELizJM6prY',
    appId: '1:902742693556:ios:e3d10185bd1c358123e9e1',
    messagingSenderId: '902742693556',
    projectId: 'opticellfinal',
    storageBucket: 'opticellfinal.firebasestorage.app',
    iosBundleId: 'com.example.opticell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnBcq0UznnDBenUK4RqZRzeELizJM6prY',
    appId: '1:902742693556:ios:e3d10185bd1c358123e9e1',
    messagingSenderId: '902742693556',
    projectId: 'opticellfinal',
    storageBucket: 'opticellfinal.firebasestorage.app',
    iosBundleId: 'com.example.opticell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlqW5-yq8cZDcDUK-W_dKiTByXSskW9gY',
    appId: '1:902742693556:web:9b6c8bfc2b7efeb823e9e1',
    messagingSenderId: '902742693556',
    projectId: 'opticellfinal',
    authDomain: 'opticellfinal.firebaseapp.com',
    storageBucket: 'opticellfinal.firebasestorage.app',
    measurementId: 'G-VEK5BNTKTN',
  );

}